apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/your-username/ecom-microservices/order-service:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: order-service-secrets
                  key: mongodb-url
            - name: MONGODB_DB
              valueFrom:
                secretKeyRef:
                  name: order-service-secrets
                  key: mongodb-database
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: order-service-secrets
                  key: jwt-secret
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
