apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: default
type: Opaque
data:
  # These are example placeholders. In production, replace with actual base64 encoded values
  mongodb-uri: bW9uZ29kYjovL2V4YW1wbGU6MjcwMTc=
  jwt-secret: c2VjcmV0LWtleS1leGFtcGxl