name: Order Service CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - "services/order-service/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "services/order-service/**"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: order_service_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run tests
        run: |
          cd services/order-service
          docker build -t order-service-test -f Dockerfile.test .
          docker run --network host order-service-test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/order-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/order-service:${{ github.sha }}
            ghcr.io/${{ github.repository }}/order-service:latest

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy to development
        run: |
          kubectl apply -f infrastructure/kubernetes/order-service/
          kubectl set image deployment/order-service order-service=ghcr.io/${{ github.repository }}/order-service:${{ github.sha }} -n development
